############################
## CHANGE THESE
############################

baseURL: "https://username.github.io/L1nkr"
title: "L1nkr"

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
markup:
  goldmark:
    renderHooks:
      image:
        enableDefault: true
